export type City = {
  name: string
  slug: string
}

export async function getCities(locale: string): Promise<City[]> {
  return [
    {"name": "Warszawa", "slug": "systemy-ppoz-warszawa"},
    {"name": "Kraków", "slug": "systemy-ppoz-krakow"},
    {"name": "Łódź", "slug": "systemy-ppoz-lodz"},
    {"name": "Wrocław", "slug": "systemy-ppoz-wroclaw"},
    {"name": "Poznań", "slug": "systemy-ppoz-poznan"},
    {"name": "Gdańsk", "slug": "systemy-ppoz-gdansk"},
    {"name": "Szczecin", "slug": "systemy-ppoz-szczecin"},
    {"name": "Bydgoszcz", "slug": "systemy-ppoz-bydgoszcz"},
    {"name": "Lublin", "slug": "systemy-ppoz-lublin"},
    {"name": "Białystok", "slug": "systemy-ppoz-bialystok"},
    {"name": "Katowice", "slug": "systemy-ppoz-katowice"},
    {"name": "Gdynia", "slug": "systemy-ppoz-gdynia"},
    {"name": "Toruń", "slug": "systemy-ppoz-torun"},
    {"name": "Radom", "slug": "systemy-ppoz-radom"},
    {"name": "Częstochowa", "slug": "systemy-ppoz-czestochowa"},
    {"name": "Rzeszów", "slug": "systemy-ppoz-rzeszow"},
    {"name": "Kielce", "slug": "systemy-ppoz-kielce"},
    {"name": "Gliwice", "slug": "systemy-ppoz-gliwice"},
    {"name": "Olsztyn", "slug": "systemy-ppoz-olsztyn"},
    {"name": "Opole", "slug": "systemy-ppoz-opole"},
    {"name": "Elbląg", "slug": "systemy-ppoz-elblag"},
    {"name": "Płock", "slug": "systemy-ppoz-plock"},
    {"name": "Gorzów Wielkopolski", "slug": "systemy-ppoz-gorzow-wielkopolski"},
    {"name": "Zielona Góra", "slug": "systemy-ppoz-zielona-gora"},
    {"name": "Kalisz", "slug": "systemy-ppoz-kalisz"},
    {"name": "Legnica", "slug": "systemy-ppoz-legnica"},
    {"name": "Koszalin", "slug": "systemy-ppoz-koszalin"},
    {"name": "Grudziądz", "slug": "systemy-ppoz-grudziadz"},
    {"name": "Jaworzno", "slug": "systemy-ppoz-jaworzno"},
    {"name": "Sopot", "slug": "systemy-ppoz-sopot"},
    {"name": "Nowy Sącz", "slug": "systemy-ppoz-nowy-sacz"},
    {"name": "Jastrzębie-Zdrój", "slug": "systemy-ppoz-jastrzebie-zdroj"},
    {"name": "Siedlce", "slug": "systemy-ppoz-siedlce"},
    {"name": "Słupsk", "slug": "systemy-ppoz-slupsk"},
    {"name": "Piła", "slug": "systemy-ppoz-pila"},
    {"name": "Ostrów Wielkopolski", "slug": "systemy-ppoz-ostrow-wielkopolski"},
    {"name": "Ruda Śląska", "slug": "systemy-ppoz-ruda-slaska"},
    {"name": "Wałbrzych", "slug": "systemy-ppoz-walbrzych"},
    {"name": "Tychy", "slug": "systemy-ppoz-tychy"},
    {"name": "Bielsko-Biała", "slug": "systemy-ppoz-bielsko-biala"},
    {"name": "Pabianice", "slug": "systemy-ppoz-pabianice"},
    {"name": "Zabrze", "slug": "systemy-ppoz-zabrze"},
    {"name": "Bytom", "slug": "systemy-ppoz-bytom"},
    {"name": "Racibórz", "slug": "systemy-ppoz-raciborz"},
    {"name": "Chorzów", "slug": "systemy-ppoz-chorzow"},
    {"name": "Lubin", "slug": "systemy-ppoz-lubin"},
    {"name": "Tarnów", "slug": "systemy-ppoz-tarnow"},
    {"name": "Biała Podlaska", "slug": "systemy-ppoz-biala-podlaska"},
    {"name": "Głogów", "slug": "systemy-ppoz-glogow"},
    {"name": "Konin", "slug": "systemy-ppoz-konin"},
    {"name": "Leszno", "slug": "systemy-ppoz-leszno"},
    {"name": "Zamość", "slug": "systemy-ppoz-zamosc"},
    {"name": "Przemyśl", "slug": "systemy-ppoz-przemysl"},
    {"name": "Kędzierzyn-Koźle", "slug": "systemy-ppoz-kedzierzyn-kozle"},
    {"name": "Tarnowskie Góry", "slug": "systemy-ppoz-tarnowskie-gory"},
    {"name": "Mysłowice", "slug": "systemy-ppoz-myslowice"},
    {"name": "Piotrków Trybunalski", "slug": "systemy-ppoz-piotrkow-trybunalski"},
    {"name": "Inowrocław", "slug": "systemy-ppoz-inowroclaw"},
    {"name": "Łomża", "slug": "systemy-ppoz-lomza"},
    {"name": "Ostrołęka", "slug": "systemy-ppoz-ostroleka"},
    {"name": "Świdnica", "slug": "systemy-ppoz-swidnica"},
    {"name": "Gniezno", "slug": "systemy-ppoz-gniezno"},
    {"name": "Żory", "slug": "systemy-ppoz-zory"},
    {"name": "Mielec", "slug": "systemy-ppoz-mielec"},
    {"name": "Suwałki", "slug": "systemy-ppoz-suwalki"}
  ]
}

